name:
  Daily crone job
  
on:
  schedule:
    - cron: "15 23 * * *"
  workflow_dispatch:  # manual triggers

jobs:
  Get-attendance-data:
    runs-on: windows-latest # run on windows
    steps:
    - name: Checkout repo content with PAT
      uses: actions/checkout@v3 # command for github, first step
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # Use the PAT instead of the default GITHUB_TOKEN to allow push by GH actions.
    - name: Set up Python # 2nd step
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run attendance scraping
      run: python automation/attendance.py # run a attendance scraping file
    - name: Check if there are any changes in attendance .csv file
      id: git-check
      run: |
        git config user.name "${{ secrets.GIT_USERNAME }}"
        git config user.email "${{ secrets.GIT_EMAIL }}"
        git add hansard_malaysia/sessions/session_15/attendance_session_15.csv
        git diff --staged --quiet || echo "changes=true" >> $env:GITHUB_ENV
    - name: Commit and push if changes
      if: env.changes == 'true' # if there are changes made, push new data to repo
      run: |
        git commit -m "updated attendance file"
        git push